name: contributor promotion
description: "Open a issue to promote you for becoming a contributor of this repository."
title: "[CONTRIBUTOR PROMOTION]"
labels: 'contributor promotion'
assignees:
  - bensofficial
body:
  - type: markdown
    attributes:
      value: |
        Nice, that you want to become a contributor of this repository.
  - type: textarea
    id: text
    attributes:
      label: Further information.
      description: If you would like to share further information, feel free to write them down.
      placeholder: "e.g.: I want to help you programming the APIs."
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this promotion, you agree to follow our [Code of Conduct](https://github.com/bensofficial/StatusInformation/blob/main/.github/CODE_OF_CONDUCT.md) as well as our [Contributing information](https://github.com/bensofficial/StatusInformation/blob/main/.github/CONTRIBUTING.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
