# From: https://linuxtut.com/automate-format-with-maven-formatter-abb8c/
name: Auto-Format
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 16
          distribution: adopt
      - name: format
        run: |
          mvn formatter:format
          mvn formatter:validate
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Auto-Format code
