name: Execution
on:
  schedule:
    # It should run at 7 am German time
    # Summer time: Germany UTC+2 -> '0 5 * * *'
    # Winter time: Germany UTC+1 -> '0 6 * * *'
    - cron:  '0 5 * * *'
jobs:
  Execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 16
          distribution: adopt
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn clean install
      - name: Load configuration file
        run: echo "${{ secrets.CONFIGFILE }}" > StatusInformation.properties
      - name: Copy jar
        run: cp target/StatusInformation-1.0-SNAPSHOT.jar .
      - name: Execution of the jar
        run: java -jar StatusInformation-1.0-SNAPSHOT.jar
